### ISSUE TITLE
get_select_precolumns() got an unexpected keyword argument 'literal_binds'

### ISSUE THREAD

**Issue by deglavs** [zzzeek/ibm-db-sa#3]
I'm getting this error when I try to run any queries on DB2:
`get_select_precolumns() got an unexpected keyword argument 'literal_binds'`

I see this issue is fixed for other databases, but not for DB2. Would it be possible to fix it?
E.g.: [https://bitbucket.org/zzzeek/sqlalchemy/commits/dd4240e43b41](https://bitbucket.org/zzzeek/sqlalchemy/commits/dd4240e43b41)

P.S., I'm trying to use this with Apache Superset Docker container, python3-dev, if that helps.
Seeing that it hasn't been tested with Python 3, I changed the Dockerfile to use Python 2.7.x instead and the issue still remains.

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/superset/viz.py", line 275, in get_payload
    df = self.get_df()
  File "/usr/local/lib/python2.7/dist-packages/superset/viz.py", line 98, in get_df
    self.results = self.datasource.query(query_obj)
  File "/usr/local/lib/python2.7/dist-packages/superset/connectors/sqla/models.py", line 560, in query
    sql = self.get_query_str(query_obj)
  File "/usr/local/lib/python2.7/dist-packages/superset/connectors/sqla/models.py", line 328, in get_query_str
    compile_kwargs={"literal_binds": True}
  File "<string>", line 1, in <lambda>
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 436, in compile
    return self._compiler(dialect, bind=bind, **kw)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 442, in _compiler
    return dialect.statement_compiler(dialect, self, **kw)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/compiler.py", line 435, in __init__
    Compiled.__init__(self, dialect, statement, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/compiler.py", line 216, in __init__
    self.string = self.process(self.statement, **compile_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/compiler.py", line 242, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/visitors.py", line 81, in _compiler_dispatch
    return meth(self, **kw)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/compiler.py", line 1715, in visit_select
    text += self.get_select_precolumns(select, **kwargs)
TypeError: get_select_precolumns() got an unexpected keyword argument 'literal_binds'
```

**Comment by foxmuller** [comment]
Have you repair?

**Comment by zzzeek** [comment]
hi sorry this is not my project please refer to https://github.com/ibmdb/python-ibmdbsa

im going to delete this repo now
